"""Check status_enum completeness

Revision ID: e9a7d25a7408
Revises: d99ff9e35597
Create Date: 2025-06-04 13:26:21.258644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9a7d25a7408"
down_revision: Union[str, None] = "d99ff9e35597"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metadata", sa.Column("lang", sa.String(), nullable=True))
    op.add_column("metadata", sa.Column("wpm", sa.Integer(), nullable=True))
    op.add_column("metadata", sa.Column("keywords", sa.Text(), nullable=True))
    op.add_column("metadata", sa.Column("vector_id", sa.String(), nullable=True))
    op.add_column("metadata", sa.Column("note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metadata", "note")
    op.drop_column("metadata", "vector_id")
    op.drop_column("metadata", "keywords")
    op.drop_column("metadata", "wpm")
    op.drop_column("metadata", "lang")
    # ### end Alembic commands ###
