name: Architecture Inventory Auto-Update

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-architecture-docs:
    name: Update Architecture Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml
          
      - name: Install Node dependencies (if package.json exists)
        run: |
          if [ -f "package.json" ]; then
            npm ci
          else
            echo "No package.json found, skipping Node.js dependencies"
          fi
          
      - name: Generate inventory
        run: |
          echo "🔍 Scanning repository for architecture changes..."
          python tools/repo_inventory.py
          
      - name: Update architecture documentation
        run: |
          echo "📝 Updating architecture documentation based on inventory..."
          python tools/update_architecture_docs.py
          
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet docs/architecture/; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "✅ No architecture documentation changes needed"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "📋 Architecture documentation changes detected"
            git diff --name-only docs/architecture/
          fi
          
      - name: Create or update PR (for pushes to main)
        if: steps.check_changes.outputs.changed == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create a new branch for the update
          BRANCH_NAME="arch-docs-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          
          # Commit changes
          git add docs/architecture/
          git commit -m "chore(docs): architecture inventory update
          
          Auto-generated documentation update based on code changes.
          
          - Updated INVENTORY.json with latest codebase scan
          - Refreshed ARCHITECTURE.md sections
          - Updated ICD.md interface specifications  
          - Synchronized TRACEABILITY.md mappings
          
          Generated by: ${{ github.workflow }} #${{ github.run_number }}"
          
          # Push the branch
          git push origin "$BRANCH_NAME"
          
          # Check if PR already exists
          EXISTING_PR=$(gh pr list --state open --label "architecture-docs" --json number --jq '.[0].number' || echo "")
          
          if [ -n "$EXISTING_PR" ]; then
            echo "📝 Updating existing PR #$EXISTING_PR"
            gh pr edit "$EXISTING_PR" --body "## 🏗️ Architecture Documentation Update
          
          This PR contains auto-generated updates to the architecture documentation based on recent code changes.
          
          ### 📊 Changes Detected
          $(git diff --name-only HEAD~1 docs/architecture/ | sed 's/^/- /')
          
          ### 🔍 What's Updated
          - **INVENTORY.json**: Latest codebase scan results
          - **ARCHITECTURE.md**: Refreshed based on current code structure
          - **ICD.md**: Updated interface specifications
          - **TRACEABILITY.md**: Synchronized code-to-test mappings
          
          ### 🤖 Automation Details
          - **Triggered by**: ${{ github.event_name }} on ${{ github.ref }}
          - **Workflow Run**: [${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Generated**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          ---
          *This PR was automatically generated by the Architecture Inventory workflow.*"
          else
            echo "📝 Creating new architecture docs PR"
            gh pr create \
              --title "chore(docs): architecture inventory update" \
              --label "architecture-docs" \
              --body "## 🏗️ Architecture Documentation Update
          
          This PR contains auto-generated updates to the architecture documentation based on recent code changes.
          
          ### 📊 Changes Detected
          $(git diff --name-only HEAD~1 docs/architecture/ | sed 's/^/- /')
          
          ### 🔍 What's Updated
          - **INVENTORY.json**: Latest codebase scan results
          - **ARCHITECTURE.md**: Refreshed based on current code structure
          - **ICD.md**: Updated interface specifications
          - **TRACEABILITY.md**: Synchronized code-to-test mappings
          
          ### 🤖 Automation Details
          - **Triggered by**: ${{ github.event_name }} on ${{ github.ref }}
          - **Workflow Run**: [${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Generated**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          ---
          *This PR was automatically generated by the Architecture Inventory workflow.*"
          fi
          
      - name: Validate changes (for PRs)
        if: github.event_name == 'pull_request' && steps.check_changes.outputs.changed == 'true'
        run: |
          echo "⚠️ Architecture documentation is out of sync with code changes"
          echo "Please run 'make arch.scan' locally and commit the updates"
          echo ""
          echo "Files that need updating:"
          git diff --name-only docs/architecture/
          exit 1
          
      - name: Archive inventory artifact
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: architecture-inventory-${{ github.sha }}
          path: |
            docs/architecture/INVENTORY.json
            docs/architecture/ARCHITECTURE.md
            docs/architecture/ICD.md
            docs/architecture/TRACEABILITY.md
          retention-days: 30
